export default {
    events: {
      SEND_CONFIRMATION_EMAIL: 'SEND_CONFIRMATION_EMAIL',
      SEND_PASSWORD_RESET_CONFIRMATION: 'SEND_PASSWORD_RESET_CONFIRMATION',
      SEND_BULK_EMAIL_NOTIFICATION: 'SEND_BULK_EMAIL_NOTIFICATION',
      SEND_SINGLE_EMAIL_NOTIFICATION: 'SEND_SINGLE_EMAIL_NOTIFICATION',
    },
    COULD_NOT_REMOVE_COMPLETED_JOB: 'COULD_NOT_REMOVE_COMPLETED_JOB',
    COULD_NOT_FETCH_COMPLETED_JOB: 'COULD_NOT_FETCH_COMPLETED_JOB',
    EMAIL_WAS_NOT_SENT: 'Email could not be sent',
  };
  